application: poised-space-127410
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:       # static then dynamic
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/spi/.*
  script: tictactoe.api
  secure: always

- url: /crons/cache_incomplete_games
  script: main.app
  login: admin

libraries:

- name: webapp2
  version: latest

- name: endpoints
  version: latest
